### ISSUE TITLE
Use YAML in jobs descriptor

### ISSUE THREAD

**Issue by benas** [j-easy/easy-jobs#8]
YAML is easier for humans to write and less error prone than JSON.

The goal is to write job descriptors in YAML instead of JSON. For example:

```yaml
---
id: 1
name: my first job
class: org.mycompany.jobs.MyFirstJob
method: doWork
---
id: 2
name: my second job
class: org.mycompany.jobs.MySecondJob
method: doWork
```
